#Fundamental Concepts of Tensorflow, using Tensorflow

## Specific concepts:

* Intro to tensors
* Getting data from tesnsors
* Manipulating tensors
* tensors and numpy
* Using @tf.function - speeds up py functions
* Using GPUs with TensorFlow or TPUs

# Intro to tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
# Create the first tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the dimesnisons of the tensor
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the vector dimension
vector.ndim

1

In [ ]:
# Now let's create a matrix:
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check the matrix dimensions
matrix.ndim

2

In [ ]:
# Let's create another martrix, specifying a data type
another_matrix = tf.constant([[10., 7],
                              [3., 2],
                              [8., 9]], dtype=tf.float16) # We specify the dtype w/ dtype= parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Check the dimensions of the new matrix
another_matrix.ndim

2

In [ ]:
# Let's create a tensor and see what happens with a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],

                      [[7, 8, 9],
                       [10, 11, 12]],

                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
# check the tensor dimensions - and watch 3D unfold before your very eyes!
tensor.ndim

3

# Here is a recap of what we have made:

* A scalar or a single number
* A vector or a number with a direction
* A matrix or a 2 dimensional array of numbers
* A tensor or an n dimensional array of numbers (where n can be any number, a 0-dim tensor is a scalar, a 1 dim tensor is a vector)

## Creating tensors with tf.Variable

In [ ]:
# create a tensor with tf.variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's change a value and see what happens
changeable_tensor[4] = 7

TypeError: ignored

In [ ]:
# We got an error -- it's not like normal programming, using assignments we need .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Now let's try that with something immutable(unchangeable)
unchangeable_tensor[0].assign(7)
unchangeable_tensor # we get an error, 10 did not mutate into 7 - due to tf.constant

AttributeError: ignored

In [ ]:
### Please understand that having to make a choice between mutable and immuitable is rare
### Always use tf.constant and change to tf.Variable later on if needed. :-)

In [ ]:
## Creating random tensors using random numbers -- to better suit the data
