<a href="https://colab.research.google.com/github/flowmasterB/tensorflow-flowmasterB-teaching/blob/main/00_tf_fundamentrals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fundamental Concepts of Tensorflow, using Tensorflow

## Specific concepts:

* Intro to tensors
* Getting data from tesnsors
* Manipulating tensors
* tensors and numpy
* Using @tf.function - speeds up py functions
* Using GPUs with TensorFlow or TPUs

# Intro to tensors

In [3]:
# Import TensorFlow
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.14.0


In [4]:
# Create the first tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the dimensions of the tensor
scalar.ndim

0

In [6]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
#Check the vector dimension
vector.ndim

1

In [8]:
# Now let's create a matrix:
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
# Check the matrix dimensions
matrix.ndim

2

In [10]:
# Let's create another martrix, specifying a data type
another_matrix = tf.constant([[10., 7],
                              [3., 2],
                              [8., 9]], dtype=tf.float16) # We specify the dtype w/ dtype= parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
# Check the dimensions of the new matrix
another_matrix.ndim

2

In [12]:
# Let's create a tensor and see what happens with a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],

                      [[7, 8, 9],
                       [10, 11, 12]],

                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
# check the tensor dimensions - and watch 3D unfold before your very eyes!
tensor.ndim

3

# Here is a recap of what we have made:

* A scalar or a single number
* A vector or a number with a direction
* A matrix or a 2 dimensional array of numbers
* A tensor or an n dimensional array of numbers (where n can be any number, a 0-dim tensor is a scalar, a 1 dim tensor is a vector)

# Creating tensors with tf.Variable

In [14]:
# create a tensor with tf.Variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# Let's change a value and see what happens
changeable_tensor[4] = 7

TypeError: ignored

In [ ]:
# We got an error -- it's not like normal programming, using assignments we need .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Now let's try that with something immutable(unchangeable)
unchangeable_tensor[0].assign(7)
unchangeable_tensor # we get an error, 10 did not mutate into 7 - due to tf.constant

In [ ]:
### Please understand that having to make a choice between mutable and immuitable is rare
### Always use tf.constant and change to tf.Variable later on if needed. :-)

# Creating Random Tensors

In [ ]:
## Creating random tensors using random numbers -- to better suit the data
## -- initialze w/ random - only at the begining of the weighting progress -
## we create 2 here
random_1=tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

## Are they equal?
random_1, random_2, random_1 == random_2


In [ ]:
## They sure are! Let's shuffle the order of the tensors next...

# Shuffling Tensors

In [ ]:
# 8/24/2023 continuinmg from random tesnors -- Shuffle a tensor - valuable when you want to shuffle
# so the inherant order doesn't effect the learning process
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [8, 2]])
not_shuffled.ndim # 2 dimensional 3,2 shape yeah?

# Shuffle the non shuffled -- run it several times to witness the shuffles
tf.random.shuffle(not_shuffled)

In [ ]:
# We can see the pairs have arranged randomly only by the 1st dimension by default
# the 1st dimension is the 1st column - originally 10, 3, 8 -- then shuffled by those pairs --
# results in 3, 8, 10 -- taking their respective pair partner with them. Let's add a seed value
# tf.random.set_seed(42) -- uncomment this line and run it with and without comments to see the behavior
# of the seed value set globally -- let's see with a local/operational level seed
tf.random.shuffle(not_shuffled, seed=42) # you will notice it changes, whereas the global method does not.

# EXERCISE!!!! READ the docs for random seed generation to understand further
# From the tensorflow docs online: https://www.tensorflow.org/api_docs/python/tf/random/set_seed

In [ ]:
|# Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds.
# This sets the global seed.
# Its interactions with operation-level seeds is as follows:
# If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
# If the global seed is set, but the operation seed is not: The system deterministically picks an operation
# seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of
# tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might
# change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
# If the operation seed is set, but the global seed is not set: A default global seed and the specified operation
# seed are used to determine the random sequence.
# *** MOST IMPORTANT FOR US --If both the global and the operation seed are set: Both seeds are used in conjunction
# to determine the random sequence.

In [ ]:
||# tf.random.set_seed(4) # global level -- uncomment run -- comment run -- do it several times to see the behavior
tf.random.shuffle(not_shuffled, seed=100) # operational level

In [ ]:
# If we want our shuffled tensors to be in the same order we have to set both global and operational
# level seeds to the same value. This will result in reproducable experiments. Shuffle with similar order
# and initialize with similar random patten, then run through the experiment. :-) ** THE WHY lol

In [ ]:
# with all that random stuff, it brings us to creating tensors using NumPy arrays!

# Creating Tensors with NumPy Arrays and Other Ways to Create Tensors

# NumPy ones https://numpy.org/doc/stable/reference/generated/numpy.ones.html

In [ ]:
# NumPy onesies lol -- this will create a tesnor filled with all ones
tf.ones([3, 4])

In [ ]:
# create a tesnor filled with all zeros
tf.zeros([10, 8])

In [ ]:
# NumPy arrays into tensors -- What is the difference? Tensors are designed to run on GPU
# (much faster computational power)
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)

# X = tf.constant(some_matrix) ** Capitalized for tensor of matrix
# y = tf.constant(vector)      ** lowercase for vector
numpy_A

In [ ]:
# convert to tensor
newTensor = tf.constant(numpy_A)
newTensor

In [ ]:
# What happens if we want a 3d tensor? ** notice the shape is (24,) -- let's reshape it.
newTensor = tf.constant(numpy_A, shape=(2, 3, 4))
newTensor

In [ ]:
# Let's add another
A = tf.constant(numpy_A, shape=(2, 3, 4)) # rename to something easier
B = tf.constant(numpy_A)
A, B # new shape has 2 groups of 3 rowed 4 column arrays -- whereas the vector(1d array w/ shape 24
## has basically 24 columns, no rows, no array groups) the 1d vectror array has 24 elements or 2 * 3 * 4
## the same as the shape we declared with shape=(2,3,4))  when reshaping you must make sure the shape matches
## in multiples i.e 2, 5, 7 = 70  or a 18 2, 3, 3 etc..

In [ ]:
# Let's try without the correct multiples
A = tf.constant(numpy_A, shape=(2, 3, 5))
B = tf.constant(numpy_A)
A, B

In [ ]:
# try another series that adds to 24
A = tf.constant(numpy_A, shape=(6, 2, 2))
B = tf.constant(numpy_A)
A, B # YEP!!!
A.ndim # We can see it's a 3D shape!

In [ ]:
# can we do 2 multiples, i.e 3,8 ?
A = tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A)
A, B # YEP!!! IT WORKED??? It did but...
A.ndim # only 2d :-( oh well... lol

In [ ]:
# NEXT UP --- Getting information from tensors

In [ ]:
A.ndim

# Get info from tensors

# Shape -- tensor.shape
# Rank -- tensor.dim
# Axis or Dimension -- tensor
# Size -- tf.size

In [ ]:
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
print(tf.__version__)

In [ ]:
# GET STUFF FREOM TENSOR
print("Datatype of every element:", rank_4_tensor.dtype)
print("The number of dimensions (rank):", rank_4_tensor.ndim)
print("The shape is:", rank_4_tensor.shape)
print("Elements along the 0th axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

In [ ]:
## Indexing and expanding
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
rank_4_tensor[:1, :1, :1, :]

In [ ]:
rank_2_tensor = tf.constant([[2, 3],
                            [4, 5]])
rank_2_tensor

In [ ]:
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
rank_2_tensor[:, -1]

In [ ]:
# add extra dim
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
# or

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1)

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0)

In [ ]:
rank_2_tensor.ndim

In [ ]:
# manipulating tensors -- tensor operations

In [ ]:
# add values to tensors w/ addition
tensorop1 = tf.constant([[10, 7],
                         [3, 4]])
tensorop1[0] + 10

In [ ]:
tensorop1

In [ ]:
tensorop1 * 100

In [ ]:
tensorop1 -10

In [ ]:
# can use functions as well -- use functions for gpu speed
tf.multiply(tensorop1, 10)

# matrix multiplication
1. Inner dims must match
2. Resulting matrix has shape of the inner dims




In [ ]:
tf.matmul(tensorop1, tensorop1)

In [ ]:
tensorop1 @ tensorop1

In [ ]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
X

In [ ]:
Y = tf.constant([[7,8],
                 [9,10],
                [11,12]])

In [ ]:
X @ tf.reshape(Y, shape=(2, 3))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

In [ ]:
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

In [ ]:
# can do same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

In [ ]:
X, Y

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes=1)

In [ ]:
tf.matmul(X, tf.transpose(Y))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

In [ ]:
# check values of Y, reshape Y, and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2, 3):", "\n", tf.reshape(Y, shape=(2,3)), "\n")

print("Y transposed:", "\n", tf.transpose(Y))

In [ ]:
tf.matmul(X, tf.transpose(Y))

In [ ]:
# Changing the data type of tensors

In [ ]:
B = tf.constant([1.7, 7.4])
B

In [ ]:
C = tf.constant([7, 10])
C

In [ ]:
tf.__version__

In [ ]:
# change from 32 to 16 float -- reduced precision -- increased speed

In [ ]:
D = tf.cast(B, dtype=tf.float16)
D

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

In [ ]:
# aggregations

In [ ]:
 # absolute values
F = tf.constant([-7, -10])
F

In [ ]:
tf.abs(F)
F

In [ ]:
# min, max, mean, sum

In [ ]:
# create random tensor
G = tf.constant(np.random.randint(0, 100, size=50))
G

In [ ]:
tf.size(G), G.shape, G.ndim

In [ ]:
# min
tf.reduce_min(G)

In [ ]:
# max
tf.reduce_max(G)

In [ ]:
# mean
tf.reduce_mean(G)

In [ ]:
# sum
tf.reduce_sum(G)

In [ ]:
# variance
tf.math.reduce_variance(tf.cast(G, dtype=tf.float32))

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(G)

In [ ]:
tfp.stats.stddev(tf.cast(G, dtype=tf.float16))

In [ ]:
# postional min and max
tf.random.set_seed(42)
H = tf.random.uniform(shape=[50])
H

In [ ]:
# find argmax - posi max
tf.argmax(H)

In [ ]:
# Index of the largest value position
H[tf.argmax(H)]

In [ ]:
# find max value of H
tf.reduce_max(H)

In [ ]:
# ck equality
H[tf.argmax(H)] == tf.reduce_max(H)

In [ ]:
 # find posi min of H
 tf.argmin(H)

In [ ]:
# find the value of min posi
H[tf.argmin(H)]

In [ ]:
# find min value of H
tf.reduce_min(H)

In [ ]:
H[tf.argmin(H)] == tf.reduce_min(H)

In [ ]:
# squeeze a tensor -- remove all 1-dim axes
tf.random.set_seed(42)
I = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
I

In [ ]:
I.shape

In [ ]:
I_squeezed = tf.squeeze(I)
I_squeezed

In [ ]:
# one-hot encoding
# liast of indices
some_list = [0, 1, 2, 3]

In [ ]:
tf.one_hot(some_list, 4)

In [ ]:
tf.one_hot(some_list, depth=4, on_value="I like donuts", off_value="I also like tacos")

In [ ]:
# tensor math operations - squares - log - square root
J = tf.range(1, 10)
J

In [ ]:
tf.square(J)

In [ ]:
tf.sqrt(tf.cast(J, dtype=tf.float32))

In [ ]:
# log
tf.math.log(tf.cast(J, dtype=tf.float32))

In [ ]:
# Tensors and NumPy
# TF interacts very well w/ NumPy array
K = tf.constant(np.array([3., 7., 10]))
K

In [ ]:
# convert back
np.array(K), type(np.array(K))

In [ ]:
K.numpy(), type(K.numpy())

In [ ]:
K = tf.constant([3.])
K.numpy()[0]

In [ ]:
# defualt types of each are little diff]
numpy_K =  tf.constant(np.array([3., 7., 10.])) # float64
tensor_K = tf.constant([3., 7. , 10.]) # float32
# check dtypes
numpy_K.dtype, tensor_K.dtype

In [ ]:
# Finding access to GPUs
import tensorflow as tf
tf.config.list_physical_devices()

In [16]:
!nvidia-smi

Wed Nov  8 22:02:48 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P0    28W /  70W |    361MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# how to run tf code on CUDA GPU
# tf will use it auto if avail