<a href="https://colab.research.google.com/github/flowmasterB/tensorflow-flowmasterB-teaching/blob/main/00_tf_fundamentrals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fundamental Concepts of Tensorflow, using Tensorflow

## Specific concepts:

* Intro to tensors
* Getting data from tesnsors
* Manipulating tensors
* tensors and numpy
* Using @tf.function - speeds up py functions
* Using GPUs with TensorFlow or TPUs

# Intro to tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.14.0


In [2]:
# Create the first tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the dimensions of the tensor
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#Check the vector dimension
vector.ndim

1

In [6]:
# Now let's create a matrix:
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Check the matrix dimensions
matrix.ndim

2

In [8]:
# Let's create another martrix, specifying a data type
another_matrix = tf.constant([[10., 7],
                              [3., 2],
                              [8., 9]], dtype=tf.float16) # We specify the dtype w/ dtype= parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# Check the dimensions of the new matrix
another_matrix.ndim

2

In [10]:
# Let's create a tensor and see what happens with a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],

                      [[7, 8, 9],
                       [10, 11, 12]],

                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
# check the tensor dimensions - and watch 3D unfold before your very eyes!
tensor.ndim

3

# Here is a recap of what we have made:

* A scalar or a single number
* A vector or a number with a direction
* A matrix or a 2 dimensional array of numbers
* A tensor or an n dimensional array of numbers (where n can be any number, a 0-dim tensor is a scalar, a 1 dim tensor is a vector)

# Creating tensors with tf.Variable

In [12]:
# create a tensor with tf.Variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's change a value and see what happens
changeable_tensor[4] = 7

TypeError: ignored

In [15]:
# We got an error -- it's not like normal programming, using assignments we need .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# Now let's try that with something immutable(unchangeable)
unchangeable_tensor[0].assign(7)
unchangeable_tensor # we get an error, 10 did not mutate into 7 - due to tf.constant

AttributeError: ignored

In [17]:
### Please understand that having to make a choice between mutable and immuitable is rare
### Always use tf.constant and change to tf.Variable later on if needed. :-)

# Creating Random Tensors

In [18]:
## Creating random tensors using random numbers -- to better suit the data
## -- initialze w/ random - only at the begining of the weighting progress -
## we create 2 here
random_1=tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

## Are they equal?
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [19]:
## They sure are! Let's shuffle the order of the tensors next...

# Shuffling Tensors

In [20]:
# 8/24/2023 continuinmg from random tesnors -- Shuffle a tensor - valuable when you want to shuffle
# so the inherant order doesn't effect the learning process
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [8, 2]])
not_shuffled.ndim # 2 dimensional 3,2 shape yeah?

# Shuffle the non shuffled -- run it several times to witness the shuffles
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 8,  2]], dtype=int32)>

In [21]:
# We can see the pairs have arranged randomly only by the 1st dimension by default
# the 1st dimension is the 1st column - originally 10, 3, 8 -- then shuffled by those pairs --
# results in 3, 8, 10 -- taking their respective pair partner with them. Let's add a seed value
# tf.random.set_seed(42) -- uncomment this line and run it with and without comments to see the behavior
# of the seed value set globally -- let's see with a local/operational level seed
tf.random.shuffle(not_shuffled, seed=42) # you will notice it changes, whereas the global method does not.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  2],
       [ 3,  4],
       [10,  7]], dtype=int32)>

# EXERCISE!!!! READ the docs for random seed generation to understand further
# From the tensorflow docs online: https://www.tensorflow.org/api_docs/python/tf/random/set_seed

In [22]:
|# Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds.
# This sets the global seed.
# Its interactions with operation-level seeds is as follows:
# If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
# If the global seed is set, but the operation seed is not: The system deterministically picks an operation
# seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of
# tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might
# change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
# If the operation seed is set, but the global seed is not set: A default global seed and the specified operation
# seed are used to determine the random sequence.
# *** MOST IMPORTANT FOR US --If both the global and the operation seed are set: Both seeds are used in conjunction
# to determine the random sequence.

SyntaxError: ignored

In [ ]:
||# tf.random.set_seed(4) # global level -- uncomment run -- comment run -- do it several times to see the behavior
tf.random.shuffle(not_shuffled, seed=100) # operational level

In [23]:
# If we want our shuffled tensors to be in the same order we have to set both global and operational
# level seeds to the same value. This will result in reproducable experiments. Shuffle with similar order
# and initialize with similar random patten, then run through the experiment. :-) ** THE WHY lol

In [24]:
# with all that random stuff, it brings us to creating tensors using NumPy arrays!

# Creating Tensors with NumPy Arrays and Other Ways to Create Tensors

# NumPy ones https://numpy.org/doc/stable/reference/generated/numpy.ones.html

In [25]:
# NumPy onesies lol -- this will create a tesnor filled with all ones
tf.ones([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [26]:
# create a tesnor filled with all zeros
tf.zeros([10, 8])

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [27]:
# NumPy arrays into tensors -- What is the difference? Tensors are designed to run on GPU
# (much faster computational power)
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)

# X = tf.constant(some_matrix) ** Capitalized for tensor of matrix
# y = tf.constant(vector)      ** lowercase for vector
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [28]:
# convert to tensor
newTensor = tf.constant(numpy_A)
newTensor

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [29]:
# What happens if we want a 3d tensor? ** notice the shape is (24,) -- let's reshape it.
newTensor = tf.constant(numpy_A, shape=(2, 3, 4))
newTensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [30]:
# Let's add another
A = tf.constant(numpy_A, shape=(2, 3, 4)) # rename to something easier
B = tf.constant(numpy_A)
A, B # new shape has 2 groups of 3 rowed 4 column arrays -- whereas the vector(1d array w/ shape 24
## has basically 24 columns, no rows, no array groups) the 1d vectror array has 24 elements or 2 * 3 * 4
## the same as the shape we declared with shape=(2,3,4))  when reshaping you must make sure the shape matches
## in multiples i.e 2, 5, 7 = 70  or a 18 2, 3, 3 etc..

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [31]:
# Let's try without the correct multiples
A = tf.constant(numpy_A, shape=(2, 3, 5))
B = tf.constant(numpy_A)
A, B

TypeError: ignored

In [32]:
# try another series that adds to 24
A = tf.constant(numpy_A, shape=(6, 2, 2))
B = tf.constant(numpy_A)
A, B # YEP!!!
A.ndim # We can see it's a 3D shape!

3

In [33]:
# can we do 2 multiples, i.e 3,8 ?
A = tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A)
A, B # YEP!!! IT WORKED??? It did but...
A.ndim # only 2d :-( oh well... lol

2

In [34]:
# NEXT UP --- Getting information from tensors

In [35]:
A.ndim

2

# Get info from tensors

# Shape -- tensor.shape
# Rank -- tensor.dim
# Axis or Dimension -- tensor
# Size -- tf.size

In [36]:
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [38]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [39]:
print(tf.__version__)

2.14.0


In [40]:
# GET STUFF FREOM TENSOR
print("Datatype of every element:", rank_4_tensor.dtype)
print("The number of dimensions (rank):", rank_4_tensor.ndim)
print("The shape is:", rank_4_tensor.shape)
print("Elements along the 0th axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
The number of dimensions (rank): 4
The shape is: (2, 3, 4, 5)
Elements along the 0th axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


In [41]:
## Indexing and expanding
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [42]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [43]:
rank_2_tensor = tf.constant([[2, 3],
                            [4, 5]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [44]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [45]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [46]:
# add extra dim
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

In [47]:
# or

In [48]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

In [49]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [4, 5]]], dtype=int32)>

In [50]:
rank_2_tensor.ndim

2

In [51]:
# manipulating tensors -- tensor operations

In [52]:
# add values to tensors w/ addition
tensorop1 = tf.constant([[10, 7],
                         [3, 4]])
tensorop1[0] + 10

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 17], dtype=int32)>

In [53]:
tensorop1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [54]:
tensorop1 * 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000,  700],
       [ 300,  400]], dtype=int32)>

In [55]:
tensorop1 -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [56]:
# can use functions as well -- use functions for gpu speed
tf.multiply(tensorop1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

# matrix multiplication
1. Inner dims must match
2. Resulting matrix has shape of the inner dims




In [57]:
tf.matmul(tensorop1, tensorop1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [58]:
tensorop1 @ tensorop1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [59]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [60]:
Y = tf.constant([[7,8],
                 [9,10],
                [11,12]])

In [61]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [62]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [63]:
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [64]:
# can do same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [65]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [66]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [67]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [68]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [69]:
# check values of Y, reshape Y, and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2, 3):", "\n", tf.reshape(Y, shape=(2,3)), "\n")

print("Y transposed:", "\n", tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3): 
 tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
 tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [70]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [71]:
# Changing the data type of tensors

In [72]:
B = tf.constant([1.7, 7.4])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>

In [73]:
C = tf.constant([7, 10])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [75]:
tf.__version__

'2.14.0'

In [76]:
# change from 32 to 16 float -- reduced precision -- increased speed

In [81]:
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [82]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [86]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

In [88]:
# aggregations

In [89]:
 # absolute values
F = tf.constant([-7, -10])
F

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [93]:
tf.abs(F)
F

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [92]:
# min, max, mean, sum

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [97]:
# create random tensor
G = tf.constant(np.random.randint(0, 100, size=50))
G

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([85, 55,  6,  0, 98, 25, 57, 56, 29, 83, 34, 85, 18, 92, 17, 13, 26,
       54, 84, 31, 35, 13, 56, 99, 40, 68, 19, 24, 67, 80, 99, 54, 61, 43,
       76, 66,  4, 10, 89, 79,  6, 49, 69, 13, 75, 30,  6, 30, 21, 55])>

In [99]:
tf.size(G), G.shape, G.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [102]:
# min
tf.reduce_min(G)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [103]:
# max
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [104]:
# mean
tf.reduce_mean(G)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [108]:
# sum
tf.reduce_sum(G)

<tf.Tensor: shape=(), dtype=int64, numpy=2384>

In [152]:
# variance
tf.math.reduce_variance(tf.cast(G, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=871.3777>

In [138]:
import tensorflow_probability as tfp
tfp.stats.variance(G)

<tf.Tensor: shape=(), dtype=int64, numpy=871>

In [149]:
tfp.stats.stddev(tf.cast(G, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=29.52>

In [157]:
# postional min and max
tf.random.set_seed(42)
H = tf.random.uniform(shape=[50])
H

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [158]:
# find argmax - posi max
tf.argmax(H)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [160]:
# Index of the largest value position
H[tf.argmax(H)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [162]:
# find max value of H
tf.reduce_max(H)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [164]:
# ck equality
H[tf.argmax(H)] == tf.reduce_max(H)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [165]:
 # find posi min of H
 tf.argmin(H)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [174]:
# find the value of min posi
H[tf.argmin(H)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [175]:
# find min value of H
tf.reduce_min(H)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [173]:
H[tf.argmin(H)] == tf.reduce_min(H)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# squeeze a tensor -- remove all 1-dim axes
