#Fundamental Concepts of Tensorflow, using Tensorflow

## Specific concepts:

* Intro to tensors
* Getting data from tesnsors
* Manipulating tensors
* tensors and numpy
* Using @tf.function - speeds up py functions
* Using GPUs with TensorFlow or TPUs

# Intro to tensors

In [3]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [4]:
# Create the first tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the dimesnisons of the tensor
scalar.ndim

0

In [6]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
#Check the vector dimension
vector.ndim

1

In [8]:
# Now let's create a matrix:
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
# Check the matrix dimensions
matrix.ndim

2

In [10]:
# Let's create another martrix, specifying a data type
another_matrix = tf.constant([[10., 7],
                              [3., 2],
                              [8., 9]], dtype=tf.float16) # We specify the dtype w/ dtype= parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
# Check the dimensions of the new matrix
another_matrix.ndim

2

In [12]:
# Let's create a tensor and see what happens with a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],

                      [[7, 8, 9],
                       [10, 11, 12]],

                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
# check the tensor dimensions - and watch 3D unfold before your very eyes!
tensor.ndim

3

# Here is a recap of what we have made:

* A scalar or a single number
* A vector or a number with a direction
* A matrix or a 2 dimensional array of numbers
* A tensor or an n dimensional array of numbers (where n can be any number, a 0-dim tensor is a scalar, a 1 dim tensor is a vector)

# Creating tensors with tf.Variable

In [14]:
# create a tensor with tf.Variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# Let's change a value and see what happens
changeable_tensor[4] = 7

TypeError: ignored

In [16]:
# We got an error -- it's not like normal programming, using assignments we need .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
# Now let's try that with something immutable(unchangeable)
unchangeable_tensor[0].assign(7)
unchangeable_tensor # we get an error, 10 did not mutate into 7 - due to tf.constant

AttributeError: ignored

In [18]:
### Please understand that having to make a choice between mutable and immuitable is rare
### Always use tf.constant and change to tf.Variable later on if needed. :-)

# Creating Random Tensors

In [19]:
## Creating random tensors using random numbers -- to better suit the data
## -- initialze w/ random - only at the begining of the weighting progress -
## we create 2 here
random_1=tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

## Are they equal?
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [20]:
## They sure are! Let's shuffle the order of the tensors next...

# Shuffling Tensors

In [21]:
# 8/24/2023 continuinmg from random tesnors -- Shuffle a tensor - valuable when you want to shuffle
# so the inherant order doesn't effect the learning process
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [8, 2]])
not_shuffled.ndim # 2 dimensional 3,2 shape yeah?

# Shuffle the non shuffled -- run it several times to witness the shuffles
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  2],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [22]:
# We can see the pairs have arranged randomly only by the 1st dimension by default
# the 1st dimension is the 1st column - originally 10, 3, 8 -- then shuffled by those pairs --
# results in 3, 8, 10 -- taking their respective pair partner with them. Let's add a seed value
# tf.random.set_seed(42) -- uncomment this line and run it with and without comments to see the behavior
# of the seed value set globally -- let's see with a local/operational level seed
tf.random.shuffle(not_shuffled, seed=42) # you will notice it changes, whereas the global method does not.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  2],
       [ 3,  4],
       [10,  7]], dtype=int32)>

# EXERCISE!!!! READ the docs for random seed generation to understand further
# From the tensorflow docs online: https://www.tensorflow.org/api_docs/python/tf/random/set_seed

In [23]:
# Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds.
# This sets the global seed.
# Its interactions with operation-level seeds is as follows:
# If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
# If the global seed is set, but the operation seed is not: The system deterministically picks an operation
# seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of
# tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might
# change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
# If the operation seed is set, but the global seed is not set: A default global seed and the specified operation
# seed are used to determine the random sequence.
# *** MOST IMPORTANT FOR US --If both the global and the operation seed are set: Both seeds are used in conjunction
# to determine the random sequence.

In [24]:
# tf.random.set_seed(4) # global level -- uncomment run -- comment run -- do it several times to see the behavior
tf.random.shuffle(not_shuffled, seed=100) # operational level

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 8,  2]], dtype=int32)>

In [25]:
# If we want our shuffled tensors to be in the same order we have to set both global and operational
# level seeds to the same value. This will result in reproducable experiments. Shuffle with similar order
# and initialize with similar random patten, then run through the experiment. :-) ** THE WHY lol

In [26]:
# with all that random stuff, it brings us to creating tensors using NumPy arrays!

# Creating Tensors with NumPy Arrays and Other Ways to Create Tensors

# NumPy ones https://numpy.org/doc/stable/reference/generated/numpy.ones.html

In [27]:
# NumPy onesies lol -- this will create a tesnor filled with all ones

tf.ones([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [32]:
# create a tesnor filled with all zeros
tf.zeros([10, 8])

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [35]:
# NumPy arrays into tensors -- What is the difference? Tensors are designed to run on GPU
# (much faster computational power)
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)

# X = tf.constant(some_matrix) ** Capitalized for tensor of matrix
# y = tf.constant(vector)      ** lowercase for vector
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [39]:
# convert to tensor
newTensor = tf.constant(numpy_A)
newTensor

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [41]:
# What happens if we want a 3d tensor? ** notice the shape is (24,) -- let's reshape it.
newTensor = tf.constant(numpy_A, shape=(2, 3, 4))
newTensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [45]:
# Let's add another
A = tf.constant(numpy_A, shape=(2, 3, 4)) # rename to something easier
B = tf.constant(numpy_A)
A, B # new shape has 2 groups of 3 rowed 4 column arrays -- whereas the vector(1d array w/ shape 24
## has basically 24 columns, no rows, no array groups) the 1d vectror array has 24 elements or 2 * 3 * 4
## the same as the shape we declared with shape=(2,3,4))  when reshaping you must make sure the shape matches
## in multiples i.e 2, 5, 7 = 70  or a 18 2, 3, 3 etc..

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [46]:
# Let's try without the correct multiples
A = tf.constant(numpy_A, shape=(2, 3, 5))
B = tf.constant(numpy_A)
A, B

TypeError: ignored

In [52]:
# try another series that adds to 24
A = tf.constant(numpy_A, shape=(6, 2, 2))
B = tf.constant(numpy_A)
A, B # YEP!!!
A.ndim # We can see it's a 3D shape!

3

In [54]:
# can we do 2 multiples, i.e 3,8 ?
A = tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A)
A, B # YEP!!! IT WORKED??? It did but...
A.ndim # only 2d :-( oh well... lol

2

In [ ]:
# NEXT UP --- Getting information from tensors